import type { Metadata } from "next";
import { inter, lexendDeca } from "@/app/fonts";
import { cn } from "@/lib/utils";
import "@/app/globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import {validateRequest} from "@/auth";
import {SessionProvider} from "@/app/SessionContext";
export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    const session = await validateRequest();


  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={cn(inter.variable, lexendDeca.variable, "font-inter")}
      >

      <SessionProvider session={session}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          themes={["light", "dark"]}
          disableTransitionOnChange
        >
          <div className="flex flex-col h-screen">{children}</div>
        </ThemeProvider>

      </SessionProvider>
      </body>
    </html>
  );
}
